name: pr-release
on:
  pull_request:
    branches: [master]
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Zip the folder
        id: zip
        run: zip -r iMW-woocommerce-custom-add-to-cart-button.zip iMW-woocommerce-custom-add-to-cart-button
      - name: Save it as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: iMW-woocommerce-custom-add-to-cart-button.zip
          path: iMW-woocommerce-custom-add-to-cart-button.zip
      // comment the artifact link in the PR
      - name: Comment artifact link
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Plugin zip / artifact available for preview: ${{ github.event.pull_request.head.repo.html_url }}/actions/runs/${{ github.run_id }}
