name: semgrep
on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
  schedule:
    - cron: "28 6 * * 4"
jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_RULES: p/default
